import type { ManifestComponent } from "@freebirdai/manifest";

/** JSON string literal safe to inline in generated TS. */
export const lit = (value: unknown): string => JSON.stringify(value ?? null);

/** A valid JS identifier derived from a component id (for import binding names). */
export const identFor = (id: string): string => {
  const cleaned = id.replace(/[^a-zA-Z0-9_$]/g, "_");
  return /^[0-9]/.test(cleaned) ? `_${cleaned}` : cleaned;
};

/**
 * POSIX relative import specifier from `fromDir` to `toFile`, both
 * repo-relative POSIX paths. Always starts with `./` or `../` and drops a
 * trailing `.ts`/`.tsx` extension (bundler-resolved).
 */
export const relativeImport = (fromDir: string, toFile: string): string => {
  const from = fromDir.replace(/\/+$/, "").split("/").filter(Boolean);
  const to = toFile.split("/").filter(Boolean);
  let i = 0;
  while (i < from.length && i < to.length && from[i] === to[i]) i++;
  const up = from.slice(i).map(() => "..");
  const down = to.slice(i);
  const parts = [...up, ...down];
  let spec = parts.join("/");
  if (!spec.startsWith(".")) spec = `./${spec}`;
  return spec.replace(/\.(t|j)sx?$/, "");
};

/** The default `grid` block for an entry lacking one (matches manifest default). */
export const DEFAULT_GRID_LITERAL = `{
      sizes: [
        { name: "compact", w: 4, h: 2, aspect: "wide" },
        { name: "half", w: 6, h: 3, aspect: "wide" },
        { name: "full", w: 12, h: 4, aspect: "wide" },
      ],
      preferredSize: "half",
      minSize: "compact",
    }`;

export const gridLiteral = (component: ManifestComponent): string =>
  component.grid ? lit(component.grid) : DEFAULT_GRID_LITERAL;

/** Standard generated-file banner. */
export const BANNER = `// Generated by @freebirdai/codegen. Re-run \`freebird init\` to regenerate.
// Component metadata is safe to edit here; keep ids in sync via \`freebird check\`.
`;
